### ISSUE TITLE
Document Known Issues 

### ISSUE THREAD

**Issue by marlenaklein-msft** [microsoft/MixedReality-AzureCommunicationServices-Sample#7]
Add documentation for known issues:

- [ ] Other users need to toggle camera off and on before the ACS user on HL2 can see it (ACS bug).
- [x] Auto sign-in does not work (doesn't grab tokens correctly / cannot join meeting.)
- [x] Doesn't decline other calls when in a meeting
- [x] Bar doesn't disappear when removed from meeting 
- [x] MSAL auth does not work on device
- [ ] Audio and camera do not work via remoting
```[tasklist]
### Tasks
- [ ] ACS bugs: crashing and hang up error
```
