### ISSUE TITLE
Polish Participants Panel List

### ISSUE THREAD

**Issue by marlenaklein-msft** [microsoft/MixedReality-AzureCommunicationServices-Sample#77]
```[tasklist]
### Tasks
- [ ] On the participants panel, there is a white checkmark that appears whenever the participant is selected. This should be removed.
- [ ] Near peripheral interactions for the participants buttons seems to be broken
- [ ] Email length should clip at two lines and not overflow into a third
- [ ] There should be arrows and the ability to scroll the participants panel
```
